# https://docs.gitlab.com/omnibus/docker/#install-gitlab-using-docker-compose
# macOS: export GITLAB_HOME=$HOME
# Linux: export GITLAB_HOME=/srv
# 可以将根据系统将 export 加入到 .bashrc or .zshrc
# 需要配置hosts: 127.0.0.1   gitlab.playground.io
version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '容器主机名，可以用宿主机IP或域名'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://你的宿主机IP或域名:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "2222:22"
      - "8929:8929"
    volumes:
      - $GITLAB_HOME/gitlab/data:/var/opt/gitlab
      - $GITLAB_HOME/gitlab/logs:/var/log/gitlab
      - $GITLAB_HOME/gitlab/config:/etc/gitlab
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - $GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab:
    driver: bridge